name: Build and Publish EVENT LOG Service
on:
  push:
    branches:
      - BAH-3008
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build-publish-docker:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        #uses: actions/checkout@v2
        uses: actions-js/push@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 8

      - name: Build with Maven
        run: mvn clean -U package

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: bahmni/event-log-service-${{ github.run_number }},bahmni/event-log-service-latest
